# -*- coding: utf-8 -*-
"""Melissa Homework - Rakamin Trial Class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VlM6PAtox2QJBcRaeMhRAqnTv4pOyy82

### Homework Rakamin Trial Class - Mini Case

# Mengukur Performa Penjualan Ritel Online

## Load Data
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('online_retail_II.csv')

df

"""## Section 1

### Create New Feature: Year
"""

df['Year'] = df['InvoiceDate']

df

pd.DatetimeIndex(df['InvoiceDate']).year

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df['Year'] = pd.DatetimeIndex(df['InvoiceDate']).year

df

"""### Filtering Data"""

df[ (df['Quantity'] >= 1) & (df['Invoice'] != 'C%' ) ]

sales = df[ (df['Quantity'] >= 1) & (df['Invoice'] != 'C%' ) ]

"""### Create New Feature: Revenue"""

df['Revenue'] = df['Quantity'] * df['Price']

df

"""### Average of Revenue per Year"""

df.groupby('Year')['Revenue'].mean().reset_index()

df.groupby('Year')['Revenue'].sum().plot(kind="bar")

"""### Interpretation
Year 2010 has seen a massive surge in revenue of more than 8 million as compared to in 2009, with a slight drop in the next year.

## Section 2

### Filtering Data

#### Customers who finished their purchases
"""

sales[sales[['Customer ID']].notnull().all(1)]

finished = sales[sales[['Customer ID']].notnull().all(1)]

"""#### Customers who canceled their purchases"""

df[df['Invoice'].str.contains('C')]

cancel = df[df['Invoice'].str.contains('C')]

"""### Number of Finished and Canceled Transactions Each Year"""

finished.groupby('Year')['Invoice'].count().reset_index()

finished.groupby('Year')['Invoice'].count().plot(kind='pie')

cancel.groupby('Year')['Invoice'].count().reset_index()

cancel.groupby('Year')['Invoice'].count().plot(kind='pie')

"""### Cancellation Rate"""

df[df['Year'] == 2009]

(1015 / 45228) * 100

df[df['Year'] == 2010]

(9919 / 522714) * 100

df[df['Year'] == 2011]

(8560 / 499429) * 100

"""### Interpretation

Looking solely at the digits, 2010 suffered the most number of cancelled orders, having surged almost 9 times compared to the previous year. However, looking at the cancellation rate per year, it displayed a substantial drop with a plummet of approximately 0.35% from 2009 to 2010. 

Following the increase of the number of customers, a higher rate of processed orders shows. This is evident from the dramatic rise of over 372.000 completed orders in 2010 compared to 2009, only to experience a 4.45% decrease of customers the following year.

2011's sales falls slightly short in contrast to the year before, suffering a loss of more than 31.000 completed orders. Despite that, the cancellation rate of 2011 is 0.19% lower than of 2010, which signals a steady decrease of cancelled orders per year.
"""